---
services:
  dme:
    image: ghcr.io/jcostom/cfdns-update:latest
    container_name: cfdns
    volumes:
      - /var/docks/cfdns:/config
    user: 1000:1000
    environment:
      - APITOKEN=cloudflare-api-token-goes-here
      - ZONEID=cloudflare-zone-id-number
      - RECORDS=list,of,hostnames,you,are,updating
      - USETELEGRAM=1
      - CHATID='Your Telegram Chat ID'
      - MYTOKEN='Your Telegram Bot Token'
      - SITENAME='Your Site Identifier'
      - TZ=America/New_York
      - DEBUG=0
    restart: unless-stopped
    network_mode: bridge
